In [9]:
import pandas as pd
import numpy as np

In [10]:
df = pd.read_csv("temp/endpoints_calculated_std.csv")

In [11]:
data = df[df.columns[3:]].to_numpy()

In [12]:
smiles = df["smiles"].to_list()

In [14]:
from legogram import LegoGram

RDKit WARNING: [21:59:22] Enabling RDKit 2019.09.2 jupyter extensions


In [15]:
legoModel = LegoGram(smiles = smiles, nworkers=8)

In [1]:
import torch
import numpy as np
from legogram.legogram.base import LegoGram
from legogram.legogram.rnn_sampler import LegoGramRNNSampler

RDKit WARNING: [00:32:16] Enabling RDKit 2019.09.2 jupyter extensions


In [2]:
!ls

CheckDataloader.ipynb  legoModel.pk	    runs
CheckSmiles.ipynb      legogram		    sampler.pk
README.md	       lg.bin		    scoring_func.py
Untitled.ipynb	       lg.tar.gz	    seqs.pk
__pycache__	       lg_2_table_data.bin  seqs_likelihood.pt
agent_state.pt	       lg_old.bin	    temp
apply_model.py	       logits_agent.pk	    train.py
archives	       logits_prior.pk	    train_agent.py
correct_smiles.pk      model.py		    train_prior.py
data		       model_reinvent.py    train_prior_reinvent
data_structs.py        model_simple.py	    train_prior_reinvent.py
experiments	       providers.py	    utils.py


In [3]:
dataset = torch.load("lg.bin")

In [4]:
list(dataset.model.lg.rules_dict.values())[-1]

2970

In [5]:
a = torch.load("seqs_likelihood.pt")

In [7]:
seqs, likelihood = a

In [14]:
np.max(seqs.cpu().numpy())

2972

In [16]:
seqs = seqs.cpu().numpy()

In [27]:
seqs[0, :][0]

1313

In [32]:
dataset.model.encode("CCO")

[7, 3, 36]

In [33]:
dataset.model.decode(np.array([7,3,36]))

'CCO'

In [35]:
from model_reinvent import RNN
Prior = RNN()

In [37]:
ckpt = torch.load("data/Prior.ckpt")
Prior.rnn.load_state_dict(ckpt)

<All keys matched successfully>

In [40]:
Prior.rnn.eval()

MultiGRU(
  (embedding): Embedding(2973, 128)
  (gru_1): GRUCell(128, 512)
  (gru_2): GRUCell(512, 512)
  (gru_3): GRUCell(512, 512)
  (linear): Linear(in_features=512, out_features=2973, bias=True)
)

In [41]:
seqs, likelihood, _ = Prior.sample(128)

In [43]:
seqs

tensor([[ 7, 13,  3,  ...,  0,  0,  0],
        [ 7, 29, 13,  ...,  0,  0,  0],
        [ 7, 18, 30,  ...,  0,  0,  0],
        ...,
        [ 7,  8,  4,  ...,  0,  0,  0],
        [ 7,  5,  9,  ...,  0,  0,  0],
        [93, 72,  5,  ...,  0,  0,  0]], device='cuda:0')

In [64]:
seqs = list(seqs.cpu().numpy())

In [71]:
seqs[1][:list(seqs[1]).index(2972)]

array([   7,   29,   13,   95,   30,    1,    1,    1,    8,    4,   11,
          5,    9,    0,    2,   23,    0,    0,    2,   43,    5,    9,
          0,    0,    0,    0,    0, 2972])

In [46]:
for i, seq in enumerate(seqs.cpu().numpy()):
    try:
        smile = dataset.model.decode(seq)
        print(smile)
        if Chem.MolFromSmiles(smile):
            valid += 1
    except:
        print("None")
        pass

None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None
None


In [57]:
seq[:21]

array([93, 72,  5,  9,  0,  0,  0,  0,  2,  8,  4, 11,  5, 12,  0,  0,  2,
       49,  2, 52,  0])

In [58]:
smile = dataset.model.decode(seq[:21])

In [59]:
smile

'N#Cc1ccccc1C(=O)Nc1ccc(N)c(Br)c1'

In [31]:
list(seqs[0, :])

[1313,
 1440,
 209,
 2421,
 532,
 1789,
 688,
 1722,
 181,
 2331,
 2565,
 2135,
 1747,
 91,
 1336,
 814,
 1886,
 1821,
 2666,
 690,
 1881,
 1711,
 1278,
 2570,
 2257,
 274,
 11,
 2428,
 419,
 274,
 2426,
 625,
 574,
 1721,
 2698,
 1576,
 938,
 2826,
 2869,
 656,
 228,
 2004,
 779,
 528,
 1284,
 1512,
 1812,
 2126,
 493,
 1527,
 1437,
 2669,
 160,
 150,
 1902,
 2844,
 2814,
 1982,
 1268,
 524,
 165,
 909,
 387,
 1486,
 892,
 491,
 584,
 541,
 889,
 1111,
 701,
 2029,
 844,
 2077,
 790,
 643,
 2823,
 70,
 42,
 88,
 2341,
 1265,
 1399,
 896,
 760,
 736,
 2196,
 1246,
 245,
 2412,
 721,
 2609,
 244,
 1639,
 1646,
 800,
 845,
 1245,
 1438,
 576,
 918,
 1393,
 2374,
 632,
 2964,
 2658,
 828,
 1205,
 2230,
 739,
 614,
 50,
 429,
 1452,
 500,
 2186,
 1479,
 598,
 680,
 2696,
 1389,
 2757,
 2,
 1640,
 914,
 1401,
 1117,
 1643,
 2312,
 2919,
 660,
 2446,
 944,
 2155,
 465,
 887,
 2302,
 2421,
 1944,
 2334]

In [29]:
dataset.model.lg.decode(list(seqs[0, :]))

IndexError: list index out of range

In [78]:
from rdkit import Chem

In [79]:
elem = 0
for idx, s in enumerate(seqs):
    try:
        
        s = list(s)
        s = s[:s.index(2972)]
        mol = dataset.model.decode(s)
        print(mol)
        if Chem.MolFromSmiles(mol):
            elem+=1
    except:
        print(None)

COCCN1CCN(C(=O)N2CCO[C@]3(CCCC(C)(C)C3)C2)CC1
C[C@H](OC1CCC1)C(=O)Nc1cc(Cl)ccc1Sc1ccccc1
CC1CC[NH+](CCNC(=O)CSc2ncnn2C)CC1
O=C(Nc1ccc2c(c1)OCO2)Nc1cc(N2CCCC2=O)ccc1F
CC(C)n1cccc1[C@@H](O)[C@H]1COc2ccccc21
Cc1ccc(Sc2ccccc2NC(=O)Cc2c[nH]nc2C)cc1
COC[C@@H](NC(=O)c1ncccc1C)C(=O)OC
COC(=O)c1ccc(C[NH+]2CCC(NC=O)CC2)o1
Cc1ccc(C[NH+]2CCCn3ncnc3C2)o1
Cc1ccc(C[NH2+][C@H](C)CCc2ccccc2)c(C)c1C
O=C(NCC1(c2ccncc2)CO1)S(=O)(=O)c1ccc(Cl)c(C(F)(F)F)c1
C[C@H]([NH2+][C@H](C)c1cccs1)c1cccc(-n2cccc2)c1
CC(=O)N1CCC(C(=O)Nc2ccc3c(c2)N(C)CCO3)CC1
CC(=CC(=O)Nc1cc(C)ccc1I)c1ccc2c(c1)OCCO2
CCCNCc1cc(Cl)ccc1O
CC(C)[C@@H]([O-])[C@H](C)S(=O)(=O)c1ccc(-c2ccc3ccccc3n2)cc1
Cn1cc(-c2ccco2)nc1NC(=O)c1coc(C2CC2)n1
None
None
COCCNC(=O)[C@@H](C)Oc1ccc(Cl)cc1N
COCc1cc(=O)c(C[NH+]2CCc3c(C)n[nH]c3C2)n[nH]1
None
None
CCC[NH+]1CC[C@@H]([NH2+][C@H](C)C2CC[NH+](C)CC2)C1
O=C(Nc1ccc(Br)cc1)N1CCC(OCc2ccccc2)CC1
COC(=O)CCCn1cc(NC(=O)c2ccc(Cl)c([N+](=O)[O-])c2)c2cccnc21
CCCOc1ccc(NC(=O)C[C@@H]2CCS(=O)(=O)C2)cc1
Cc1ccc(C)n1-c1cccc(NC(=

In [80]:
print(elem/128)

0.765625


In [38]:
dataset.vocsize

2973

In [39]:
dataset.model.vocsize

2973

In [40]:
len(dataset.model.lg.rules_dict)

2971

In [41]:
from torch.utils.data import DataLoader

In [50]:
def collate_fn(arr):
    """Function to take a list of encoded sequences and turn them into a batch"""
    print(type(arr))
    print(arr[0])
    max_length = max([len(seq) for seq in arr])
    print(max_length)
    collated_arr = Variable(torch.zeros(len(arr), max_length))
    print(collated_arr.shape)
    for i, seq in enumerate(arr):
        collated_arr[i, :seq.size(0)] = seq
    return collated_arr

In [51]:
train_loader = DataLoader(dataset, batch_size=512, collate_fn=collate_fn)

In [52]:
def Variable(tensor):
    """Wrapper for torch.autograd.Variable that also accepts
       numpy arrays directly and automatically assigns it to
       the GPU. Be aware in case some operations are better
       left to the CPU."""
    if isinstance(tensor, np.ndarray):
        tensor = torch.from_numpy(tensor)
    if torch.cuda.is_available():
        return torch.autograd.Variable(tensor).cuda()
    return torch.autograd.Variable(tensor)


In [53]:
val = None
for it in train_loader:
    val = it
    break

<class 'list'>
tensor([   7,   71,    9,    0,    0,   16,   10,    2,   43,   29,    6,    8,
           4,   11,   18,   30,    1,    1,   62,    6,    1,    1,   34,    6,
          42,    4,   16,    0, 2971])
40
torch.Size([512, 40])


In [57]:
val[0, :]

tensor([7.0000e+00, 7.1000e+01, 9.0000e+00, 0.0000e+00, 0.0000e+00, 1.6000e+01,
        1.0000e+01, 2.0000e+00, 4.3000e+01, 2.9000e+01, 6.0000e+00, 8.0000e+00,
        4.0000e+00, 1.1000e+01, 1.8000e+01, 3.0000e+01, 1.0000e+00, 1.0000e+00,
        6.2000e+01, 6.0000e+00, 1.0000e+00, 1.0000e+00, 3.4000e+01, 6.0000e+00,
        4.2000e+01, 4.0000e+00, 1.6000e+01, 0.0000e+00, 2.9710e+03, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00,
        0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00], device='cuda:0')

In [24]:
legoModel.rules_dict.values()

dict_values([0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 180, 181, 182, 183, 184, 185, 186, 187, 188, 189, 190, 191, 192, 193, 194, 195, 196, 197, 198, 199, 200, 201, 202, 203, 204, 205, 206, 207, 208, 209, 210, 211, 212, 213, 214, 215, 216, 217, 218, 21

 ...]